### ISSUE TITLE
Замечания по коду игры

### ISSUE THREAD

**Issue by sergey-shambir** [intmpg/TvimsDefence#1]
- размещать код обычных функций в заголовочных файлах - посредственное решение, такой файл потом можно включить только в один CPP. Код из game.h следует перенести в game.cpp, при этом объявления функций оставить в game.h
- код функции startGame слишком большой. Часть её подзадач (инициализация, обработка ввода, рисование) можно вынести в отдельные функции, а кое-где код и вовсе можно сократить. Вот эти объявления явно лишние:

``` cpp
std::list<Entity*>::iterator it;
std::list<Entity*>::iterator it2;
```

итераторы можно объявлять в месте использования, в том числе с помощью auto, а можно и вообще их не использовать благодаря range based for: http://en.cppreference.com/w/cpp/language/range-for
Код, который сейчас лежит в game.h в строках 147-180, следует перевести с итераторов на range based for.
- для всех остальных h файлов также следует создать парные cpp файлы и перенести туда определения функций, оставив в h только их объявления.

P.S. про различие между объявлениями и определениями функций см. Бъёрн Страуструп, Язык Программирования C++, глава 7.

**Comment by intmpg** [comment]
исправил
