### ISSUE TITLE
Замечания по Game.cpp

### ISSUE THREAD

**Issue by sergey-shambir** [intmpg/TvimsDefence#2]
## функция radiusAnim
- Требуется убрать магическое число 500 (заменив константой или чем-то осмысленным), dX/dY объединить в sf::Vector2f и считать как

``` cpp
sf::Vector2f dist = pos.x - sf::Vector2f(500.f, 500.f);
```
- В условии `if (dX*dX + dY*dY > attackDistance)` следует вместо выражения использовать функцию; нужно создать отдельный файл для математических функций и поместить туда функцию `lengthSqr`, возвращающую квадрат длины вектора типа `sf::Vector2f`.
- магическое число 10 в `spriteCursor.setPosition(pos.x + 10, pos.y);`
## Остальное

Условие и действие не надо писать в одну строку:

``` cpp
for (auto& it : entities) { window.draw(it->sprite); }
//////////////////////////////
for (auto& it : entities)
{
    window.draw(it->sprite);
}
```

Это встречается ещё в нескольких местах в файле.

**Comment by intmpg** [comment]
Исправил

**Comment by sergey-shambir** [comment]
Из-за `if (it->name == "ZombieEnemy") {`, `if (it2->name == "Bullet") {` возникает слишком большая вложенность отступов. Для решения проблемы надо инвертировать условие и использовать ключевое слово continue.

``` cpp
if (it->name != "ZombieEnemy")
    continue;
if (it ...
```

**Comment by sergey-shambir** [comment]
Код надо переписать на комбинацию erase и remove_if

``` cpp
for (std::list<Entity*>::iterator it = entities.begin(); it != entities.end();)
{
    if ((*it)->life == false)   {
        if ((*it)->name == "ZombieEnemy") { 
            level.score++; 
        } //åñëè óäàëèëè âðàãà, òî ïðèáàâëÿåì î÷êè èãðîêó
        it = entities.erase(it);
    }
    else   it++;
}
```

Пример того, как переписывать:

``` cpp
bool _is_crash(Bullet * bull) {
    return bull->life == false;
}
void eventBulletDestroy(Lists & lists, Hero & hero, float time) {
    lists.bullets.erase( remove_if(lists.bullets.begin(), lists.bullets.end(), _is_crash), lists.bullets.end());
}
/**********************************/
void eventBulletDestroy(Lists & lists, Hero & hero, float time) {
    auto is_crash = [](Bullet *bull) { return !(bull->life); };
    lists.bullets.erase( remove_if(lists.bullets.begin(), lists.bullets.end(), is_crash), lists.bullets.end());
}
```

**Comment by intmpg** [comment]
Исправил

**Comment by sergey-shambir** [comment]
- поправка `time = time / 800;` выглядит как хак, какой смысл имеет время, делённое на 800? Исправление темпа игры следует делать в другом месте.
- условие надо объединить оператором &&:

``` cpp
if (event.type == Event::MouseButtonPressed)//åñëè íàæàòà êëàâèøà ìûøè
if (event.key.code == Mouse::Left)
```
- почему именно 5 в `it->health -= 5;` ?
- в функции gameUpdate следует уменьшить глубину вложенности и отступов с помощью инструкции `contunue;`
- слишком много параметров передаётся в функцию `startGame`, не стоит передавать больше 4 параметров.
