### ISSUE TITLE
Замечания по LifeBar.cpp

### ISSUE THREAD

**Issue by sergey-shambir** [intmpg/TvimsDefence#3]
- имена полей и переменных s, t, bar2, pH, hH, max непонятные, остаётся неясным их предназначение. Следует сформулировать более понятные для постороннего названия на русском и написать на английском.
- слишком много магических чисел, особенно максимальное число здоровья и какие-то поправки в setPosition. Нужны константы.

**Comment by intmpg** [comment]
Исправил

**Comment by sergey-shambir** [comment]
Магических чисел по-прежнему слишком много, нужны именованные константы. Также есть проблемы с форматированием кода

``` cpp
if (playerHealth >= 0) {
    bar2.setTextureRect(IntRect(0, 0, playerHealthSize.x + playerHealth, playerHealthSize.y));
}
else { bar2.setTextureRect(IntRect(0, 0, playerHealthSize.x, playerHealthSize.y)); }
```

**Comment by intmpg** [comment]
Исправил
