### ISSUE TITLE
Замечания по Entity и x/y

### ISSUE THREAD

**Issue by sergey-shambir** [intmpg/TvimsDefence#4]
В коде во многих местах используются раздельные x/y, даже там, где можно объединить их с помощью sf::Vector2f. С вектором проще работать, потому что многие операции совершаются сразу над вектором из 2 значений (в SFML, к примеру, определено умножение вектора на скаляр).
- яркий пример - класс Entity и конструкторы унаследованных от него классов

**Comment by intmpg** [comment]
Исправил
